title:  Seonghui Lee
tagline:  
author:
  name: 'Paul Le'
  twitter:  paululele

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-44147916-1'

menu:
- {name: 'Home', url: '..'}
- {name: 'Research', url: 'research.html'}
- {name: 'Teaching', url: 'teaching.html'}
- {name: 'Vitae', url: '../files/cvLee.pdf'}
- {name: 'Links', url: 'links.html'}
#- {name: 'Contact', url: 'contact.html'}

social:
#- {icon: 'github', link: 'https://www.github.com/seonghuilee'}
- {icon: 'university', link: 'https://www.essex.ac.uk/people/leese60806/seonghui-lee'}
- {icon: 'twitter', link: 'https://twitter.com/seonghuilee'}
- {icon: 'envelope', link: 'mailto:s.lee@essex.ac.uk'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer (http://fontawesome.io/icons/)
